//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antipina_OlnineStickerStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_product
    {
        public int ID_of_ordered_product { get; set; }
        public Nullable<int> ID_of_order { get; set; }
        public Nullable<int> ID_of_product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Stickers Stickers { get; set; }
    }
}
