//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antipina_OlnineStickerStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_product = new HashSet<Order_product>();
        }
    
        public int ID_of_order { get; set; }
        public Nullable<int> ID_of_user { get; set; }
        public string Type_of_payment { get; set; }
        public Nullable<int> ID_of_delivery { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<int> Cost_of_order { get; set; }
        public string Order_status { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_product> Order_product { get; set; }
    }
}
